CREATE DATABASE remises_online;

USE remises_online;

CREATE TABLE User(
    UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Email VARCHAR(320) NOT NULL,
    Trips INT DEFAULT 0,
    Cellphone INT NOT NULL,
    Country VARCHAR(50) NOT NULL,
    CurrentLocation VARCHAR(150) NOT NULL,
    Deleted TINYINT DEFAULT 0,
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Deleted_at TIMESTAMP NULL DEFAULT NULL
);

ALTER TABLE Rider
ADD CONSTRAINT email UNIQUE KEY( email );