CREATE TABLE DriversOnTrip(
	DriverID INT NOT NULL,
    TripID INT NULL DEFAULT 0,
    Start_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DriverID) REFERENCES Driver(DriverID),
    FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);

CREATE TABLE DriversWorking(
	DriverID INT NOT NULL,
    IsOnATrip TINYINT NOT NULL DEFAULT 0,
    Latitude DECIMAL NOT NULL,
    Longitude DECIMAL NOT NULL,
    FOREIGN KEY (DriverID) REFERENCES Driver(DriverID)
);