CREATE TABLE Driver (
    DriverID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Email VARCHAR(320) NOT NULL,
    DNI INT NOT NULL,
    DNIFrontImageURL VARCHAR(100) NOT NULL,
    DNIBackImageURL VARCHAR(100) NOT NULL,
    Cellphone INT NOT NULL,
    Country VARCHAR(50) NOT NULL DEFAULT 'ARGENTINA',
    CurrentLocationLatitude VARCHAR(150) NOT NULL,
    CurrentLocationLongitude VARCHAR(150) NOT NULL,
    DriverApproved TINYINT NOT NULL DEFAULT 0,
    Trips INT DEFAULT 0,
    CurrentlyInATrip TINYINT NOT NULL DEFAULT 0,
    Deleted TINYINT DEFAULT 0,
    Created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Deleted_at TIMESTAMP NULL DEFAULT NULL
);

ALTER TABLE Driver
ADD CONSTRAINT email UNIQUE KEY( email );

ALTER TABLE Driver
ADD CONSTRAINT dni UNIQUE KEY( DNI );