USE remises_online;

CREATE TABLE Trips (
    TripID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RiderID INT NOT NULL,
    DriverID INT NULL DEFAULT NULL,
    Country VARCHAR(50) NOT NULL DEFAULT 'ARGENTINA',
    StartLocation VARCHAR(50) NOT NULL,
    FinalLocation VARCHAR(50) NOT NULL,
    DistanceKM INT NOT NULL DEFAULT 0,
    PriceARS DECIMAL(13, 2) NOT NULL DEFAULT 0,
    Start_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DriverID) REFERENCES Driver(DriverID),
    FOREIGN KEY (RiderID) REFERENCES Rider(RiderID)
);

CREATE TABLE TripsQueue (
    TripQueueID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TripID INT NOT NULL,
    Queue_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);

CREATE TABLE TripsInProcess (
    TripInProcessID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TripID INT NOT NULL,
    Start_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);

CREATE TABLE TripsCompleted (
    TripCompletedID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TripID INT NOT NULL,
    Completion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TripID) REFERENCES Trips(TripID)
);